name: CI
on:
  push:
      paths-ignore:
        - 'README.md'
      branches:
        - master
  pull_request:
      paths-ignore:
        - 'README.md'
      branches:
        - master
jobs:
  test:
    name: Julia ${{ matrix.version }} - R ${{ matrix.R }}- ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.4'
          - '1'
        R:
          - '4.0'
        os:
          # - ubuntu-latest # linux currently doesn't work because of lib issues
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.R }}
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: julia-actions/julia-uploadcodecov@v0.1
        if:  ${{ startsWith(matrix.os, 'ubuntu') && startsWith(matrix.julia-version, '1.4') }}
